id = "jsonl"
name = "JSONL"
version = "0.1.0"
schema_version = 1
authors = ["Ofer Affias <ofer.affias@gmail.com>"]
description = "JSON Lines (JSONL) syntax highlighting support for Zed"
repository = "https://github.com/yourusername/jsonl-syntax"

[grammars.json]
repository = "https://github.com/tree-sitter/tree-sitter-json"
rev = "001c28d7a29832b06b0e831ec77845553c89b56d"
